sudo: required

services:
  - docker

before_install:
  - docker build -t holhas/docker-travis-aws-simple -f Dockerfile.dev .

script:
  - docker run -e CI=true holhas/docker-travis-aws-simple npm run test -- --coverage --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-473449314582"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"