sudo: required

services:
  - docker

before_install:
  - docker build -t holhas/docker-travis-aws-simple -f Dockerfile.dev .

script:
  - docker run holhas/docker-travis-aws-simple npm run test -- --coverage
